import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Theme } from "@radix-ui/themes";
import { ThemeProvider } from "next-themes";
// import Providers from "./redux/provider";
import Providers from "./redux3/provider/provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider attribute="className">
        <Theme appearance="inherit">
          <Providers>
            <body className={inter.className}>{children}</body>
          </Providers>
        </Theme>
      </ThemeProvider>
    </html>
  );
}
